version: "3.8"
services:
  web:
    restart: always
    container_name: "ddd-front"
    build:
      context: "./front"
      target: "dev"
    tty: true
    depends_on:
      - db
      - api
    ports:
      - 13000:3000
    volumes:
      - ./front:/work/app
    command:
      ["yarn","dev"]
  api:
    restart: always
    container_name: "ddd-api"
    build:
      context: "./api"
      target: "dev"
    tty: true
    depends_on:
      - db
    ports:
      - 5555:5555
    volumes:
      - ./api/api:/work/src/api
      - ./api/tests:/work/src/tests
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/dev
    command:
      ["uvicorn", "api.main:app", "--reload", "--host", "0.0.0.0", "--port", "5555"]

  db:
    image: postgres:14
    restart: always
    container_name: "ddd-sql"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - ./docker/postgresql/initdb:/docker-entrypoint-initdb.d

  chatdb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: dev
    volumes:
      - ./docker/mongo:/data/db
